### ISSUE TITLE
Booleans are red instead of peach

### ISSUE THREAD

**Issue by danscheer** [catppuccin/bat#24] opened 2024-07-25 12:56 UTC
Noticed that the theme sets the boolean color correctly to peach, but in the bat output all booleans are red. 
Using catppuccin mocha.

**Comment by sgoudham** [comment] 2024-08-02 10:48
Hey 👋,

Could you provide a sample file that highlights the booleans as red?

Thanks!

**Comment by danscheer** [comment] 2024-08-02 15:16
Hi, thanks for the reply. When i looked for it again I could not reproduce it, but some other things catched my eyes: 

Yazi uses bat for its code-preview (and therefore the catppuccin bat-theme, because it is bat). They are almost the same on a lot of file formats, but in json i got this difference: 

bat in YAZI
<img width="1014" alt="Screenshot 2024-08-02 at 16 58 34" src="https://github.com/user-attachments/assets/f3c4bfeb-ed3b-4466-9181-f5f084d4a42a">
 
bat CLI (in kitty on macos)
<img width="633" alt="Screenshot 2024-08-02 at 16 58 53" src="https://github.com/user-attachments/assets/9ee70579-02b8-4a28-b714-8bdb09027b04">

I could only find this for json so far, every other format i tested was identical. 

Also, the catppuccin theme for bat differs a lot from the catppuccin theme for neovim (with default settings): 

PHP: 

bat
<img width="999" alt="Screenshot 2024-08-02 at 17 07 06" src="https://github.com/user-attachments/assets/8fec8403-8328-4ca4-b2e1-e90de4d231f6">

nvim
<img width="997" alt="Screenshot 2024-08-02 at 17 07 29" src="https://github.com/user-attachments/assets/f9b98fe6-c7a7-49d4-9851-dbf8374bc8d1">

JS: 

bat 
<img width="584" alt="Screenshot 2024-08-02 at 17 09 47" src="https://github.com/user-attachments/assets/6b997645-256d-4ede-8af8-aa9fdcf29af0">

neovim
<img width="594" alt="Screenshot 2024-08-02 at 17 10 11" src="https://github.com/user-attachments/assets/7fc9eecb-39a1-49f2-aa4b-dc6eae4b5b5b">


It is absolutely possible that this is coming from a bad configuration of my machine, so when you say everything seems fine i have to check my configs again. But at least im curious what you say about the YAZI difference. 

Thank you!


@edit 

Noticed that AstroVim loads for 1 sec the correct (identical with bat) colors, after 1 sec the inlayhints are loaded and after that the colors look like in my screenshot. So I would defenetly say there is something wrong in my config. 

@edit2

found out that its about semantic highlighting (https://www.reddit.com/r/neovim/comments/12gvms4/this_is_why_your_higlights_look_different_in_90/). Since bat doesnt load any lsp it will look different in NeoVim.

**Comment by sgoudham** [comment] 2024-08-05 13:36
> They are almost the same on a lot of file formats, but in json i got this difference:

I'm a bit surprised at the difference in yazi vs using the CLI, maybe @uncenter has some insights into that difference since the highlights shouldn't change from bat and yazi :thinking: 

> Also, the catppuccin theme for bat differs a lot from the catppuccin theme for neovim (with default settings):

I see that you've done some research yourself but it's worth mentioning that it's not just because semantic highlights is disabled. Bat and Neovim use entirely different theming engines/parsers, bat using textmate (hence why it's generated from vscode) and neovim using treesitter. It is impossible to make them identical 100% but we try our best! 

I'll close this issue as the original error could not be reproduced. I'll most likely raise another issue for the JSON differences if that's something bat can fix on its end.

**Closed as completed by sgoudham** 2024-08-05 13:36 UTC

**Comment by uncenter** [comment] 2024-08-05 14:31
Hmm, one of your comparisons between Bat and Yazi showed different results on a JSON file - I'm not seeing that, the outputs of the two look exactly the same for me! Interstingly, your somehow different Yazi highlighting looks *more correct* compared to our VS Code port.

**Yazi**:
![CleanShot 2024-08-05 at 10 29 00@2x](https://github.com/user-attachments/assets/24a94aaa-57c7-4f8f-893c-c93c49c36f04)

**Bat**:
![CleanShot 2024-08-05 at 10 28 29@2x](https://github.com/user-attachments/assets/656dd7c9-891f-4fb5-bce7-78ad3be6e354)

**VS Code**:
![CleanShot 2024-08-05 at 10 28 44@2x](https://github.com/user-attachments/assets/5ebac1a2-7d63-4b80-ad35-d997df2320d8)

**Comment by uncenter** [comment] 2024-08-08 13:48
@danscheer just to confirm you are using the latest version of our theme files for bat? How are you configuring it for bat? Do you have Yazi's syntect theme option pointing to the same file?
